spring.profiles.active: development
---
spring:
  profiles: cloud
  data:
    neo4j:
      uri: bolt://${SPRING_NEO4J_HOST:neo4j}:7687
      username: neo4j
      password: 654321
---
spring:
  profiles: development
  data:
    neo4j:
      uri: bolt://${SPRING_NEO4J_HOST:neo4j}:7687
      username: neo4j
      password: 654321
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: bolt://${SPRING_NEO4J_HOST:neo4j}:7687
      username: neo4j
      password: 654321
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  data:
    neo4j:
      uri: bolt://${SPRING_NEO4J_HOST:neo4j}:7687
      username: neo4j
      password: 654321
eureka:
  client:
    enabled: false
